name: K8s Resource Calculator

on:
  push:
    branches:
      - main # Substitua pelo nome da branch que você deseja executar o workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install kubernetes
          
      - name: Create Kind cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
           version: "v0.11.1"

      - name: Set up kubeconfig
        run: |
         echo "KUBECONFIG=$(kind get kubeconfig-path)" >> $GITHUB_ENV

      - name: Run Kube Resource Calculator
        run: python kube_resource_calculator.py default
